---

- name: Configure properly etcd cluster.
  hosts: all
  become: True
  tasks:
    - name: Ensure that etcd is present
      apt:
        name: etcd
        state: latest

    - name: Ensure that etcd is properly configured
      template:
        src: etcd.conf
        dest: /etc/etcd/etcd.conf

    - name: Ensure etcd is running
      service:
        name: etcd
        state: started
        enabled: True
