apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: stable
apiServer:
  certSANs:
  - "172.28.128.124"
controlPlaneEndpoint: "172.28.128.124:6443"
etcd:
  external:
    endpoints:
    - http://172.28.128.121:2379
    - http://172.28.128.122:2379
    - http://172.28.128.123:2379
    caFile: /etc/etcd/ca.pem
    certFile: /etc/etcd/kubernetes.pem
    keyFile: /etc/etcd/kubernetes-key.pem
networking:
  podSubnet: 192.168.0.0/16
