---

- name: Prerequites Setup.
  hosts: all
  become: true
  tasks:
    - name: Set timezone to Asia/Jakarta
      timezone:
        name: Asia/Jakarta
    
    - name: sudo vagrant.
      command: usermod -aG sudo vagrant

    - name: Install package requirement.
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - unzip
        - htop

    - name: Add Docker apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present
      register: add_repository_key
      ignore_errors: true

    - name: Add Docker repository.
      apt_repository:
        repo: "{{ docker_apt_repository }}"
        state: present
        update_cache: true
      vars:
        docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"

    - name: Update Debian package
      apt:
        update_cache: yes

    - name: Install Docker and dependencies.
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - docker-ce
        - containerd.io
      notify: docker status

    - name: Add user vagrant to docker group.
      user:
        name: vagrant
        group: docker

    - name: Remove swap file from /etc/fstab.
      mount:  
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a

    - name: Disable swap after swap
      command: sed -i '/ swap / s/^/#/' /etc/fstab

    - name: Add key for kubernetes.
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add repository for kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    
    - name: Install kubernetes binaries.
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - kubelet
        - kubeadm
        - kubectl
        - nfs-client

  handlers:
    - name: docker status
      service:
        name: docker
        state: started
